"""Chat route — POST /api/chat.

Accepts a single user question, retrieves relevant public legal chunks via
hybrid search, and returns a grounded plain-language legal information
response generated by a local Ollama chat model.

PRIVACY / SECURITY RULES (must not be loosened without team review):
    * Raw message text is processed in memory only and never written to
      any database table, log, or error message.
    * No generated answer text is persisted anywhere.
    * No chat history is stored. This route is stateless between calls.
    * privacy_safe_answer_logs is never written to by this module.
    * No public AI API is called at any point in this route.
    * Error responses are intentionally generic — they never echo the user's
      message, the database DSN, credentials, or stack traces.
"""

from __future__ import annotations

import json

from fastapi import APIRouter, Depends, HTTPException
from fastapi import status as http_status
from fastapi.responses import StreamingResponse

from app.core.config import Settings, get_settings
from app.schemas.chat import (
    ChatRequest,
    ChatResponse,
    LegalCitation,
    StructuredResultResponse,
)
from app.services.chat_service import ChatService
from app.services.ollama_chat_client import OllamaChatClientError
from app.services.ollama_embedding_client import EmbeddingClientError

router = APIRouter(tags=["chat"])


def _parse_structured_sections(answer: str) -> dict[str, str]:
    sections: dict[str, str] = {}
    current: str | None = None
    body_lines: list[str] = []
    headers = {
        "Short answer",
        "What this means",
        "Typical next steps",
        "Official sources",
        "Important caution",
    }
    for raw in answer.splitlines():
        line = raw.strip()
        if line.endswith(":") and line[:-1] in headers:
            if current:
                sections[current] = "\n".join(body_lines).strip()
            current = line[:-1]
            body_lines = []
            continue
        if current:
            body_lines.append(raw)
    if current:
        sections[current] = "\n".join(body_lines).strip()
    return sections


def _to_list_items(text: str) -> list[str]:
    items: list[str] = []
    for raw in text.splitlines():
        line = raw.strip()
        if not line:
            continue
        if line[:2].isdigit() and line[2:3] in (".", ")"):
            line = line[3:].strip()
        elif line[:1].isdigit() and line[1:2] in (".", ")"):
            line = line[2:].strip()
        elif line.startswith(("-", "*", "•")):
            line = line[1:].strip()
        if line:
            items.append(line)
    return items


def _to_payload_2(chat: ChatResponse) -> StructuredResultResponse:
    sections = _parse_structured_sections(chat.answer)
    short_answer = sections.get("Short answer", "").strip()
    if not short_answer:
        # fallback: first paragraph if model did not follow section format
        short_answer = chat.answer.strip().split("\n\n")[0].strip()

    eligibility_checklist = _to_list_items(sections.get("What this means", ""))
    if not eligibility_checklist and sections.get("Important caution"):
        eligibility_checklist = _to_list_items(sections["Important caution"])

    next_steps = _to_list_items(sections.get("Typical next steps", ""))

    citations = [
        LegalCitation(
            title=chunk.citation,
            url=chunk.official_url or "",
            snippet=chunk.snippet,
        )
        for chunk in chat.used_chunks
    ]

    return StructuredResultResponse(
        short_answer=short_answer,
        eligibility_checklist=eligibility_checklist,
        next_steps=next_steps,
        citations=citations,
        disclaimer=chat.disclaimer,
    )


@router.post(
    "/api/chat",
    response_model=StructuredResultResponse,
    summary="Generate a grounded legal information response",
    description=(
        "Accept a single user question, retrieve the most relevant active "
        "legal chunks via hybrid vector+keyword search (Reciprocal Rank "
        "Fusion), and generate a plain-language legal information response "
        "using a local Ollama chat model. Answer is grounded exclusively in "
        "retrieved public legal source text. No public AI APIs are called. "
        "Raw message text is never stored."
    ),
)
async def chat(
    body: ChatRequest,
    settings: Settings = Depends(get_settings),
) -> StructuredResultResponse:
    """Generate a grounded chat response from retrieved legal chunks.

    The raw message is processed in memory and never written to any table.
    Error messages never echo the user's message, the database DSN,
    credentials, or internal stack traces.
    """
    service = ChatService(settings)

    try:
        raw = await service.generate_chat_response(
            message=body.message,
            top_k=body.top_k,
            selected_category=body.selected_category,
            conversation=[t.model_dump() for t in body.conversation],
        )
        return _to_payload_2(raw)
    except OllamaChatClientError:
        # Local Ollama chat model is unreachable or returned an invalid
        # response. Raw message is not echoed.
        raise HTTPException(
            status_code=http_status.HTTP_503_SERVICE_UNAVAILABLE,
            detail={
                "status": "error",
                "error_code": "CHAT_MODEL_UNAVAILABLE",
                "message": (
                    "Local chat model is not available. "
                    "Ensure Ollama is running: ollama serve"
                ),
                "privacy_mode": "local-first",
            },
        )
    except EmbeddingClientError:
        # Ollama embedding service unreachable during retrieval (local or cloud).
        # Raw message is not echoed.
        raise HTTPException(
            status_code=http_status.HTTP_503_SERVICE_UNAVAILABLE,
            detail={
                "status": "error",
                "error_code": "CHAT_RETRIEVAL_UNAVAILABLE",
                "message": (
                    "Embedding service is not available. "
                    "Check OLLAMA_BASE_URL, OLLAMA_API_KEY, and OLLAMA_EMBED_MODEL."
                ),
                "privacy_mode": "local-first",
            },
        )
    except Exception:
        # Database error or unexpected server fault.
        # Raw message, DSN, and stack traces are not echoed.
        raise HTTPException(
            status_code=http_status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail={
                "status": "error",
                "error_code": "CHAT_ERROR",
                "message": "An internal error occurred during chat response generation.",
                "privacy_mode": "local-first",
            },
        )


@router.post(
    "/api/chat/stream",
    summary="Stream a grounded chat response (SSE)",
    description=(
        "Same privacy and grounding rules as POST /api/chat. Emits "
        "text/event-stream events: token deltas while the local model "
        "generates, then a final done event with the full ChatResponse JSON."
    ),
)
async def chat_stream(
    body: ChatRequest,
    settings: Settings = Depends(get_settings),
) -> StreamingResponse:
    """Stream chat tokens then return the complete grounded response."""
    service = ChatService(settings)

    async def event_generator():
        try:
            async for event in service.stream_chat_events(
                message=body.message,
                top_k=body.top_k,
                selected_category=body.selected_category,
                conversation=[t.model_dump() for t in body.conversation],
            ):
                yield f"data: {json.dumps(event, ensure_ascii=False)}\n\n"
        except OllamaChatClientError:
            err = {
                "type": "error",
                "error_code": "CHAT_MODEL_UNAVAILABLE",
                "message": (
                    "Local chat model is not available. "
                    "Ensure Ollama is running: ollama serve"
                ),
            }
            yield f"data: {json.dumps(err)}\n\n"
        except EmbeddingClientError:
            err = {
                "type": "error",
                "error_code": "CHAT_RETRIEVAL_UNAVAILABLE",
                "message": (
                    "Local embedding service is not available. "
                    "Ensure Ollama is running: ollama serve"
                ),
            }
            yield f"data: {json.dumps(err)}\n\n"
        except Exception:
            err = {
                "type": "error",
                "error_code": "CHAT_ERROR",
                "message": "An internal error occurred during chat response generation.",
            }
            yield f"data: {json.dumps(err)}\n\n"

    return StreamingResponse(
        event_generator(),
        media_type="text/event-stream",
        headers={
            "Cache-Control": "no-cache",
            "Connection": "keep-alive",
            "X-Accel-Buffering": "no",
        },
    )
