"""Chat route — POST /api/chat.

Accepts a single user question, retrieves relevant public legal chunks via
hybrid search, and returns a grounded plain-language legal information
response generated by a local Ollama chat model.

PRIVACY / SECURITY RULES (must not be loosened without team review):
    * Raw message text is processed in memory only and never written to
      any database table, log, or error message.
    * No generated answer text is persisted anywhere.
    * No chat history is stored. This route is stateless between calls.
    * privacy_safe_answer_logs is never written to by this module.
    * No public AI API is called at any point in this route.
    * Error responses are intentionally generic — they never echo the user's
      message, the database DSN, credentials, or stack traces.
"""

from __future__ import annotations

from fastapi import APIRouter, Depends, HTTPException
from fastapi import status as http_status

from app.core.config import Settings, get_settings
from app.schemas.chat import ChatRequest, ChatResponse
from app.services.chat_service import ChatService
from app.services.ollama_chat_client import OllamaChatClientError
from app.services.ollama_embedding_client import EmbeddingClientError

router = APIRouter(tags=["chat"])


@router.post(
    "/api/chat",
    response_model=ChatResponse,
    summary="Generate a grounded legal information response",
    description=(
        "Accept a single user question, retrieve the most relevant active "
        "legal chunks via hybrid vector+keyword search (Reciprocal Rank "
        "Fusion), and generate a plain-language legal information response "
        "using a local Ollama chat model. Answer is grounded exclusively in "
        "retrieved public legal source text. No public AI APIs are called. "
        "Raw message text is never stored."
    ),
)
async def chat(
    body: ChatRequest,
    settings: Settings = Depends(get_settings),
) -> ChatResponse:
    """Generate a grounded chat response from retrieved legal chunks.

    The raw message is processed in memory and never written to any table.
    Error messages never echo the user's message, the database DSN,
    credentials, or internal stack traces.
    """
    service = ChatService(settings)

    try:
        return await service.generate_chat_response(
            message=body.message,
            top_k=body.top_k,
            selected_category=body.selected_category,
        )
    except OllamaChatClientError:
        # Local Ollama chat model is unreachable or returned an invalid
        # response. Raw message is not echoed.
        raise HTTPException(
            status_code=http_status.HTTP_503_SERVICE_UNAVAILABLE,
            detail={
                "status": "error",
                "error_code": "CHAT_MODEL_UNAVAILABLE",
                "message": (
                    "Local chat model is not available. "
                    "Ensure Ollama is running: ollama serve"
                ),
                "privacy_mode": "local-first",
            },
        )
    except EmbeddingClientError:
        # Local Ollama embedding service is unreachable during retrieval.
        # Raw message is not echoed.
        raise HTTPException(
            status_code=http_status.HTTP_503_SERVICE_UNAVAILABLE,
            detail={
                "status": "error",
                "error_code": "CHAT_RETRIEVAL_UNAVAILABLE",
                "message": (
                    "Local embedding service is not available. "
                    "Ensure Ollama is running: ollama serve"
                ),
                "privacy_mode": "local-first",
            },
        )
    except Exception:
        # Database error or unexpected server fault.
        # Raw message, DSN, and stack traces are not echoed.
        raise HTTPException(
            status_code=http_status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail={
                "status": "error",
                "error_code": "CHAT_ERROR",
                "message": "An internal error occurred during chat response generation.",
                "privacy_mode": "local-first",
            },
        )
