import { palette, radii, spacing, shadows, layout, cardStandard, warningNotice } from './tokens'

export { palette, radii, spacing, shadows, layout, cardStandard, warningNotice }

/**
 * Semantic colors — maps Authoritative Legal tokens + legacy aliases for existing components.
 */
export const colors = {
  parchment: palette.parchment,
  parchmentTint: palette.parchmentTint,
  backgroundBase: palette.backgroundBase,
  brandNavy: palette.brandNavy,
  brandBronze: palette.brandBronze,
  brandBronzeLight: palette.brandBronzeLight,
  bronzeTint: palette.bronzeTint,
  surfaceWhite: palette.surfaceWhite,
  textPrimary: palette.textPrimary,
  textMuted: palette.textMuted,

  cream: palette.backgroundBase,
  creamMuted: '#FAF8F4',
  creamWarm: '#EBE6DC',
  bronze: palette.brandBronze,
  bronzeLight: palette.brandBronzeLight,
  bronzeDark: palette.brandBronzeDark,
  gold: palette.brandBronze,
  goldLight: palette.brandBronzeLight,
  goldDark: palette.brandBronzeDark,
  navy: palette.brandNavy,
  navyMuted: '#2A3544',
  sage: palette.brandBronze,
  sageLight: palette.brandBronzeLight,
  forest: palette.brandNavy,
  forestMuted: '#2A3544',
  primary: palette.brandBronze,
  primaryDark: palette.brandNavy,
  primaryLight: palette.brandBronzeLight,
  background: palette.backgroundBase,
  surface: palette.surfaceWhite,
  border: palette.border,
  text: palette.textPrimary,
  textSecondary: palette.textSecondary,
  disclaimerBg: palette.parchmentTint,
  disclaimerBorder: palette.brandBronze,
  accent: palette.brandBronze,
  disclaimerText: palette.textPrimary,
  riskLowBg: '#D1FAE5',
  riskLowText: '#047857',
  riskLowBorder: '#D1FAE5',
  riskMediumBg: '#FEF3C7',
  riskMediumText: '#C2410C',
  riskMediumBorder: '#FEF3C7',
  riskHighBg: '#FEE2E2',
  riskHighText: '#991B1B',
  riskHighBorder: '#FEE2E2',
  dangerBg: '#F0EBE3',
  white: palette.surfaceWhite,
  onPrimary: palette.onNavy,
  onNavy: palette.onNavy,
} as const
