#!/usr/bin/env python3
"""Validate an eCFR Title 8 JSON preview before database insertion.

This script is the pre-flight check for the JSON preview produced by
``scripts/fetch_ecfr_title8_sample.py``. It confirms that the preview
file has the shape later ingestion steps will expect, so we can fail
loudly *before* writing anything to PostgreSQL.

Privacy
-------
The eCFR (Electronic Code of Federal Regulations) is *public* legal-
source data. This validator only reads a JSON preview that was
generated from public eCFR Title 8 content. It does NOT read user
questions, user-provided facts, chat logs, or any private data. It
does NOT write to PostgreSQL, does NOT generate embeddings, and does
NOT call Ollama, OpenAI, Anthropic, or any other AI API.

Usage
-----
    # Validate the newest preview under data/ecfr_samples/
    python scripts/validate_ecfr_title8_preview.py

    # Validate a specific preview file
    python scripts/validate_ecfr_title8_preview.py \\
        --preview-file data/ecfr_samples/title8_sample_preview_2026-05-12.json

Exit codes
----------
* 0 — all validations passed.
* 1 — one or more validations failed (each problem is printed).
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

DEFAULT_PREVIEW_GLOB = "data/ecfr_samples/title8_sample_preview_*.json"

TOP_LEVEL_REQUIRED_FIELDS: tuple[str, ...] = (
    "source_name",
    "source_url",
    "source_date",
    "targeted_section_count",
    "found_section_count",
    "missing_sections",
    "sections",
)

SECTION_REQUIRED_FIELDS: tuple[str, ...] = (
    "citation",
    "section_number",
    "title",
    "official_url",
    "text_snippet",
    "text_length",
    "source_date",
)

EXPECTED_TARGET_SECTIONS: tuple[str, ...] = (
    "208.7",
    "208.4",
    "245.1",
    "274a.12",
    "239.1",
)

CITATION_PREFIX = "8 CFR §"
OFFICIAL_URL_PREFIX = "https://www.ecfr.gov/current/title-8/section-"


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def _parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Validate an eCFR Title 8 JSON preview file generated by "
            "scripts/fetch_ecfr_title8_sample.py. Reads public legal-"
            "source data only; never touches user data."
        ),
    )
    parser.add_argument(
        "--preview-file",
        default=None,
        help=(
            "Path to a specific preview JSON file. "
            f"Default: newest file matching {DEFAULT_PREVIEW_GLOB} "
            "(relative to the current working directory; run from the repo root)."
        ),
    )
    return parser.parse_args(argv)


# ---------------------------------------------------------------------------
# File discovery / loading
# ---------------------------------------------------------------------------


def _find_newest_preview() -> Path | None:
    """Return the newest preview file under data/ecfr_samples/, or None."""
    candidates = list(Path().glob(DEFAULT_PREVIEW_GLOB))
    if not candidates:
        return None
    candidates.sort(key=lambda p: p.stat().st_mtime, reverse=True)
    return candidates[0]


def _load_preview(path: Path) -> dict[str, Any]:
    with path.open("r", encoding="utf-8") as fp:
        return json.load(fp)


# ---------------------------------------------------------------------------
# Validation
# ---------------------------------------------------------------------------


def _validate_top_level(preview: dict[str, Any], errors: list[str]) -> None:
    for field in TOP_LEVEL_REQUIRED_FIELDS:
        if field not in preview:
            errors.append(f"missing top-level field: {field!r}")


def _validate_section(section: Any, index: int, errors: list[str]) -> None:
    if not isinstance(section, dict):
        errors.append(f"sections[{index}] is not a JSON object")
        return

    label = section.get("section_number") or f"<index {index}>"

    for field in SECTION_REQUIRED_FIELDS:
        if field not in section:
            errors.append(f"section {label}: missing field {field!r}")

    citation = section.get("citation")
    if isinstance(citation, str):
        if not citation.startswith(CITATION_PREFIX):
            errors.append(
                f"section {label}: citation must start with {CITATION_PREFIX!r} "
                f"(got {citation!r})"
            )
    elif "citation" in section:
        errors.append(f"section {label}: citation must be a string (got {type(citation).__name__})")

    official_url = section.get("official_url")
    if isinstance(official_url, str):
        if not official_url.startswith(OFFICIAL_URL_PREFIX):
            errors.append(
                f"section {label}: official_url must start with "
                f"{OFFICIAL_URL_PREFIX!r} (got {official_url!r})"
            )
    elif "official_url" in section:
        errors.append(
            f"section {label}: official_url must be a string "
            f"(got {type(official_url).__name__})"
        )

    text_snippet = section.get("text_snippet")
    if not isinstance(text_snippet, str) or not text_snippet.strip():
        errors.append(f"section {label}: text_snippet must be a non-empty string")

    text_length = section.get("text_length")
    if not isinstance(text_length, int) or isinstance(text_length, bool) or text_length <= 0:
        errors.append(
            f"section {label}: text_length must be an int > 0 (got {text_length!r})"
        )


def _validate_expected_sections_present(
    preview: dict[str, Any], errors: list[str]
) -> list[str]:
    """Return the list of expected section numbers that are missing."""
    sections = preview.get("sections")
    if not isinstance(sections, list):
        return list(EXPECTED_TARGET_SECTIONS)

    present = {
        s.get("section_number")
        for s in sections
        if isinstance(s, dict) and isinstance(s.get("section_number"), str)
    }
    missing = [n for n in EXPECTED_TARGET_SECTIONS if n not in present]
    if missing:
        errors.append(
            "missing expected target sections: " + ", ".join(missing)
        )
    return missing


def validate_preview(preview: dict[str, Any]) -> tuple[list[str], list[str]]:
    """Return ``(errors, missing_expected_sections)``."""
    errors: list[str] = []
    _validate_top_level(preview, errors)

    sections = preview.get("sections")
    if isinstance(sections, list):
        for i, section in enumerate(sections):
            _validate_section(section, i, errors)
    elif sections is not None:
        errors.append("'sections' must be a list")

    missing_expected = _validate_expected_sections_present(preview, errors)
    return errors, missing_expected


# ---------------------------------------------------------------------------
# Reporting
# ---------------------------------------------------------------------------


def _print_report(
    preview_path: Path,
    preview: dict[str, Any],
    errors: list[str],
    missing_expected: list[str],
) -> None:
    print("eCFR Title 8 JSON preview validation")
    print(f"  preview file        : {preview_path}")
    print(f"  source_date         : {preview.get('source_date')!r}")
    print(f"  found_section_count : {preview.get('found_section_count')!r}")
    print(
        f"  expected target ({len(EXPECTED_TARGET_SECTIONS)}): "
        + ", ".join(EXPECTED_TARGET_SECTIONS)
    )
    if missing_expected:
        print(f"  missing expected    : {', '.join(missing_expected)}")
    else:
        print("  missing expected    : (none)")

    if errors:
        print(f"  status              : FAIL ({len(errors)} issue(s))")
        for err in errors:
            print(f"    - {err}")
    else:
        print("  status              : PASS")


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------


def main(argv: list[str] | None = None) -> int:
    args = _parse_args(argv)

    if args.preview_file is not None:
        preview_path = Path(args.preview_file)
        if not preview_path.is_file():
            print(f"ERROR: --preview-file does not exist: {preview_path}")
            return 1
    else:
        found = _find_newest_preview()
        if found is None:
            print(f"ERROR: no preview file matches {DEFAULT_PREVIEW_GLOB}.")
            print(
                "       Run `python scripts/fetch_ecfr_title8_sample.py` first, "
                "and run this validator from the repo root."
            )
            return 1
        preview_path = found

    try:
        preview = _load_preview(preview_path)
    except json.JSONDecodeError as exc:
        print(f"ERROR: {preview_path} is not valid JSON: {exc}")
        return 1
    except OSError as exc:
        print(f"ERROR: could not read {preview_path}: {exc}")
        return 1

    if not isinstance(preview, dict):
        print(f"ERROR: {preview_path} top-level JSON is not an object.")
        return 1

    errors, missing_expected = validate_preview(preview)
    _print_report(preview_path, preview, errors, missing_expected)

    return 1 if errors else 0


if __name__ == "__main__":
    sys.exit(main())
